{"name": "Создание заказа без авторизации", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался статус 401, но получен 200.\nassert 200 == 401\n +  where 200 = <Response [200]>.status_code", "trace": "self = <Tests.test_create_order.TestCreateOrderAuthorized object at 0x000001F3953A7110>, register_new_user = (<Response [200]>, ['ivan221295@yandex.ru', 'nzmqbcvfkb', 'ybaikyqnro'])\n\n    @allure.title(\"Создание заказа без авторизации\")\n    @allure.description(\n        \"Проверка, что при попытке создания заказа без передачи токена авторизации возвращается статус 401.\")\n    def test_create_order_without_authorization(self, register_new_user):\n        payload = {\"ingredients\": [\"61c0c5a71d1f82001bdaaa7a\"]}\n    \n        with allure.step(\"Отправка POST-запроса на создание заказа без токена авторизации\"):\n            response = requests.post(f\"{Urls.BASE_URL}{Urls.ORDERS}\", json=payload)\n    \n        with allure.step(\"Проверка, что статус-код равен 401 (отказ в авторизации)\"):\n>           assert response.status_code == 401, f\"Ожидался статус 401, но получен {response.status_code}.\"\nE           AssertionError: Ожидался статус 401, но получен 200.\nE           assert 200 == 401\nE            +  where 200 = <Response [200]>.status_code\n\nTests\\test_create_order.py:36: AssertionError"}, "description": "Проверка, что при попытке создания заказа без передачи токена авторизации возвращается статус 401.", "steps": [{"name": "Отправка POST-запроса на создание заказа без токена авторизации", "status": "passed", "start": 1753020599681, "stop": 1753020599893}, {"name": "Проверка, что статус-код равен 401 (отказ в авторизации)", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался статус 401, но получен 200.\nassert 200 == 401\n +  where 200 = <Response [200]>.status_code\n", "trace": "  File \"C:\\Users\\ikhri\\Documents\\GitHub\\Diplom_2\\Tests\\test_create_order.py\", line 36, in test_create_order_without_authorization\n    assert response.status_code == 401, f\"Ожидался статус 401, но получен {response.status_code}.\"\n"}, "start": 1753020599893, "stop": 1753020599894}], "attachments": [{"name": "log", "source": "bb1f5623-b69e-418f-9c75-0262582a3b01-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "cbec4784-5ddf-4e49-9ebd-b1cdcc51f829-attachment.txt", "type": "text/plain"}], "start": 1753020599681, "stop": 1753020599895, "uuid": "649ae6d8-140b-4b56-a939-cc094bea5c4a", "historyId": "d0b4f1dab600e34d09525b8accfc0693", "testCaseId": "d0b4f1dab600e34d09525b8accfc0693", "fullName": "Tests.test_create_order.TestCreateOrderAuthorized#test_create_order_without_authorization", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrderAuthorized"}, {"name": "host", "value": "DESKTOP-T2S04D8"}, {"name": "thread", "value": "19120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_create_order"}]}